# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-12-01 07:34:11
"""
import arcpy

def Model1():  # Model1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"e:\sw_nt\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    centroid_2_ = "centroid"

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
    centroid = arcpy.management.CalculateGeometryAttributes(in_features=centroid_2_, geometry_property=[["Lat", "POINT_Y"], ["Long", "POINT_X"]], coordinate_system="PROJCS[\"NAD_1983_BC_Environment_Albers\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",1000000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-126.0],PARAMETER[\"Standard_Parallel_1\",50.0],PARAMETER[\"Standard_Parallel_2\",58.5],PARAMETER[\"Latitude_Of_Origin\",45.0],UNIT[\"Meter\",1.0]]", coordinate_format="DMS_DIR_FIRST")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="W:\\for\\RNI\\RNI\\General_User_Data\\CSostad\\FCBC_FILE_MAP__INSET\\FCBC_Site_FileNo_REF_mmmyyyy_85X14_inset.gdb", workspace="W:\\for\\RNI\\RNI\\General_User_Data\\CSostad\\FCBC_FILE_MAP__INSET\\FCBC_Site_FileNo_REF_mmmyyyy_85X14_inset.gdb"):
        Model1()
